#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

TrayIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QkCFQYWfQ585wAAAB1pVFh0Q29tbWVudAAA"
    "AAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAA3UlEQVQ4y6WTQQqDMBBF32hv4MpVr+JNuhF6"
    "BEHoSvAMFrrxHG56la668gatv4uaoCI2xYEQ/iT/50+SMUnsiYidsSlg39jesyzBzDQRH1xe"
    "kq0JHJbk+60EIMvroa3OHNNkKhxLGlYdOPLj2XsSMMNZXru0F4pcrW7lmCY8nj1r+H4rGR2+"
    "zSwGiEby0FZnQkScEPAys9gAX/eW/TWc5fX8GX+dvMT+Dv4hLbEBApg+Wah976BrCk6Xa/DJ"
    "WV7TNYVfU9cUGp0EDbdfEowfySdDZ0lImv/E0A6c9sUHLAm1x3t0arAAAAAASUVORK5CYII=")
getTrayIconData = TrayIcon.GetData
getTrayIconImage = TrayIcon.GetImage
getTrayIconBitmap = TrayIcon.GetBitmap
getTrayIconIcon = TrayIcon.GetIcon

#----------------------------------------------------------------------
TrayIconPaused = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QkCFSQRRNivZAAAAB1pVFh0Q29tbWVudAAA"
    "AAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAA5ElEQVQ4y6WTTQqDMBCF36g3cOXKq9iTdCN4"
    "BKHQleAZLLjxHG68SkHoqieo5nVRI0kUtfggODPmfeRnIiRxRh5OahMgP23PcbcgIjTgStdJ"
    "yhogcM1dfQMAJGmpmiJDHIUm2CepVlegzc/XezYBsPIkLXV5BgV6r/pPHIWWKY5CfOILAKCr"
    "oeNRRAKSozeZVVNkcCGm+r5340FEfA+A6urbwrQGMfPprAbrivYg5tlYffCvaQG43h+7y3el"
    "b8QDgLbKD0HMvK3yOWZb5QRweOj5JIGpkebi0S9JkLQ78egLNN/FF0ZbrhbVIrc5AAAAAElF"
    "TkSuQmCC")
getTrayIconPausedData = TrayIconPaused.GetData
getTrayIconPausedImage = TrayIconPaused.GetImage
getTrayIconPausedBitmap = TrayIconPaused.GetBitmap
getTrayIconPausedIcon = TrayIconPaused.GetIcon

