#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

TrayIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAPdSURBVEiJnZZdbBRVFMd/5+5Ou5VSaFOCtlEQYuKDxDRFUqQNVUoqlaBgfBF5kYhPEA2K"
    "DUFTTTCAFeqDmhATQ+LHgxoTE1GgrRRsu0I/tHyUVrAKxeKWAl3obne3nePDdNrddks3nuRk"
    "bmbunN89/3vumRFVBWDv++89kp6e/lEkEikBhBRMRPB4PLu3v7Zj17STVBVV5UBN9clmf6NG"
    "oxFN1a5f79cvv/o8XL1/77tunMnudUGRaGRFYeFjqCp37tzGVtuZROILuGOUkegISwuX+fyn"
    "ml7/4MA+zfq0snHWP+YHhNBwpr3qpct2i4nP2PJaxGJRECd9MYKIYOI8/v5gMEh+fj7LlhZl"
    "5IRvVM76y/xU9MxG75JHi7N8/8qvh3LkQTNZMhGDiMEYgxHHJd7NxDgUGiIjI4Os9Bha/3Fa"
    "3uOlkpWdQ3bWHPJyco0HOeKdDDAiqMAvJ5tm3OThSJhFeTkcP7iJp97aSbihnT9ausnu7cMe"
    "vA1eFk0BiBFQKC5Zkah9wl44xXGy7nu+21NB+YZXuHfkLDwxj5utbZzr/JthjWlosaybChAD"
    "OAGFsU2WCYjrQ7euEjy1n/INW5gfaUXD/eDNIG2lxWCXMOqRtVva7cPJJQKON5yYVppYaIBA"
    "QxVlz77M/Eg7hPvB66PjfBdtfwYZeHErO3ZVHwaYNoPS0tKkJTo02MeRmu2sWreZ+2K/w3A/"
    "eNJoP3OBjsshnn+niU8++2I8XhLA2CEWRw2JEyZ0O8CRmvUUl28kb/Sss3IxnO7o4kJfjDVv"
    "HiUrd0FCvOQAgfra+oT7I8O3uFb/NqVPb+J+uxMNBwChqb2bnpuGispafJm5U+RMChCEsrKy"
    "BHm+qSpiZcVGFphuNBQAtWn87RJX7vhYW/kjaffMxe1rdwVMkQq4dtFP5uxsFvoCaDAAOsKJ"
    "tktci85hbeVhLN/spMHvCjh27Nj4uK9xP4WL50I0iI5EqTt9kauhTPLLqjjVcoaSkuLxck4Z"
    "sHr1agBCQ0E2V/ewZsnDtLQ2c65ngOwHCnhh57d4LN9EhbnVkCrAta8Pfcj5G3PYerCTzeuL"
    "qHhjG/MWFiSccMQp4WSEGSXy+xtZV/wQy598DnyZzFtYkLA/k8s5KUBEzJ59uxMeuBK512Qm"
    "4izcbSzxCBExqmq7GUxp2zOZk0X8MdTJH1oD2F5xZhpwOmRC+imDHJbBYNuj4wARp/EAYFmW"
    "v629ddp6nglixKCqtLa1Ynktv/vMq6oqInbvld5tDQ0/19TWHV1Oin8VSUwtr9Xc29v7KmCr"
    "qsqYLAbwjLkr7v8CjPkoMKqq9n8UnRbOfJKMNwAAAABJRU5ErkJggg==")
getTrayIconData = TrayIcon.GetData
getTrayIconImage = TrayIcon.GetImage
getTrayIconBitmap = TrayIcon.GetBitmap
getTrayIconIcon = TrayIcon.GetIcon

